 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  instr_tuning:
    # data_dir: ${env.data_dir}/datasets
    data_type: images

    build_info:
      annotations:
        train:
          storage: /home/henry/OFA-MMInstr/MultiInstruct/mminstr_dataset/bl_train1K/train.tsv

      vis_root: /data/henry/MultiInstruct
      images:
        storage: /home/henry/OFA-MMInstr/MultiInstruct
